# Dockerfile.ui
FROM python:3.12-slim

WORKDIR /ui
COPY requirements.txt .
RUN pip install --no-cache-dir streamlit -r requirements.txt

COPY ui/ ./ui
ENV PYTHONPATH=/ui
EXPOSE 8501
CMD ["streamlit", "run", "ui/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
